### ISSUE TITLE
Compatibility with Zepto, Minified.js, jquip and others?

### ISSUE THREAD

**Issue by IngwiePhoenix** [evanmoran/oj#17]
I just wanted to ask if the state of compatibility with known jQuery alternative is currently tested or known? I want to see if I can get away from jQuery to a smaller, thinner alternative.

**Comment by evanmoran** [comment]
I planned for it to work with Zepto as it uses very little of jQuery's features, but I didn't yet try it (jquery 2.0 is getting smaller!). By default oj picks up the global $ if such is defined. If not, just set `oj.$ = zepto` after oj loads. I use oj.$ everywhere internally for this purpose. Let me know how it works for you!

**Comment by IngwiePhoenix** [comment]
I just read the code and noticed what you ment. Also saw quite some nice API that I didn't see in the docs! (extendInto(), for instance).

I'll let you know if I managed to do some more testing! :)

**Comment by evanmoran** [comment]
Closing for now as I'm focused on OJ v2.0. Please add this back in after the 2.0 release if it doesn't work for you!
