### ISSUE TITLE
OJ and OJ... o.o

### ISSUE THREAD

**Issue by IngwiePhoenix** [evanmoran/oj#18]
Okay, I am just too tempted.

I started on making up a concept for a project that combines two OJ projects that I know into one:
- OJ: http://github.com/musictheory/oj
- OJ(js): This one.

My resulting, still draft, concept: https://github.com/IngwiePhoenix/o.o

Opinions, thoughts? :)

**Comment by evanmoran** [comment]
This was a cool concept :)
