### ISSUE TITLE
ojml: Docs about it?

### ISSUE THREAD

**Issue by IngwiePhoenix** [evanmoran/oj#19]
Within  `oj.js`, I saw the term `ojml` and a parser pop up, but did not find anything about it inside the docs, so far. Could you maybe explain or document it? Thanks!

**Comment by evanmoran** [comment]
OJML is an intermediate form of HTML/CSS similar to React's shadow dom (but also with css!). I'll be sure to include docs for it, thank you!

**Comment by evanmoran** [comment]
Closing for now. OJ 2.0 on the way!
